name: Almalinux Build

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-almalinux94

    steps:
      - name: Checkout
        uses: actions/checkout@main
#      - name: Collect Workflow Telemetry
#        uses: catchpoint/workflow-telemetry-action@v2
      - name: Build gemc
        run: |
          ./ci/build_gemc.sh
      - name: Copy gemc binary
        uses: actions/upload-artifact@v4
        with:
          name: gemc
          path: |
            /cvmfs/oasis.opensciencegrid.org/jlab/geant4/bin
            /cvmfs/oasis.opensciencegrid.org/jlab/geant4/api

