name: Experiments Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:
  pull_request:
    types:
      # only run workflow when a commit is pushed to a PR branch
      # instead of running for all other PR events
      - synchronize

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-fedora36
    outputs:
      matrix:  ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Creates list of gcards
        uses: actions/checkout@main
      - id: set-matrix
        run: |
          export JSON=$( ./ci/gcards_to_test.sh )
          echo generate-matrix: $JSON
          echo "matrix=$( echo "$JSON" | tr -d '\n' )" >> $GITHUB_OUTPUT
  

  test:
    needs: generate-matrix
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-g4v10.7.4-fedora36-cvmfs
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1.8.7
      - name: ${{ matrix.detector }} tests
        run: |
          ./ci/experiments_test.sh -g ${{ matrix.gcard }}



